name: ros2-talker-listener
version: '0.1'
summary: ROS 2 Talker/Listener Example
description: |
 This example launches a ROS 2 talker and listener.

confinement: devmode
base: core24

parts:
 ros-demos:
   plugin: colcon
   source: https://github.com/ros2/demos.git
   source-branch: jazzy
   source-subdir: demo_nodes_cpp
   stage-packages: [ros-jazzy-ros2launch]

apps:
 ros2-talker-listener:
   command: opt/ros/jazzy/bin/ros2 launch demo_nodes_cpp talker_listener.launch.py
   extensions: [ros2-jazzy]
